trigger:
- main

pool:
  vmImage: ubuntu-20.04


steps:
  - task: CMake@1
#- script: cmake .
#  workingDirectory: $(System.DefaultWorkingDirectory)
#- script: make
#  workingDirectory: $(System.DefaultWorkingDirectory)
